### ISSUE TITLE
del dependency API uses promises not callbacks 

### ISSUE THREAD

**Issue by SirJackovich** [joellongie/jlgulp#4]
In your build tasks you use the del dependency and it has been updated to use promises, not callbacks please update your repo.

**Comment by joellongie** [comment]
Thanks Jacob, this repo has been deprecated for a while and really only up here now for the youtube video.  If you are looking for a newer gulp version of this please see https://github.com/joellongie/superCell.  If I have time though I will try and update this build.  Thanks 👍
